// The site's own identity, in one place, because six different files need to
// agree on it: the metadata base, every canonical URL, the sitemap, robots.txt,
// the OG card and the JSON-LD. A second copy of the origin is how a canonical
// tag ends up pointing at a preview deployment.
//
// SERVER-SIDE ONLY. `NEXT_PUBLIC_SITE_URL` would survive into a client bundle,
// but the Vercel fallback below would not -- `VERCEL_PROJECT_PRODUCTION_URL` is
// unprefixed, so it is undefined in the browser and the chain would silently
// resolve to localhost there. Everything that reads this module (metadata
// exports, sitemap, robots, structured data) runs on the server; keep it that
// way rather than adding a client-safe branch, which would just be a second
// answer to "what is our origin".

export const SITE_NAME = "DriverPit";

// One sentence, and it is the one Google shows under the title on the home
// result. Leads with the thing people search for ("Formula 1 driver" + "six
// tries") and names the two features no competing F1 -dle has, because those
// are the queries this site can actually win.
export const SITE_DESCRIPTION =
  "Guess the mystery Formula 1 driver in six tries. A free daily F1 guessing game with unlimited practice rounds and real-time 1v1 duels against other players.";

// Shown as the OG card's subtitle, so it is shorter than the description and
// does not repeat the title.
export const SITE_TAGLINE = "The daily Formula 1 driver guessing game";

// The site-wide social card, generated by app/opengraph-image.tsx. It lives
// here rather than in that route because BOTH ends need it: the route exports
// its own `size` and `alt` from these values, and `buildPageMetadata` names the
// URL explicitly on every page.
//
// That explicit naming is not belt-and-braces, it is the whole thing working.
// Next's file convention attaches the card by merging it into the *segment's*
// resolved metadata -- but a deeper segment that exports an `openGraph` object
// REPLACES the resolved one outright (`target.openGraph = resolveOpenGraph(
// source.openGraph, …)` in next/dist/lib/metadata/resolve-metadata.js), and the
// static-file merge only re-adds an image for a segment that has an image file
// of its own. Every page here goes through buildPageMetadata, which sets
// `openGraph` for the per-page og:title -- so all nine pages silently dropped
// the card and shipped with no og:image at all. Found by `npm run seo:audit`
// on 2026-08-07; the file existed and rendered, and nothing referenced it.
//
// The URL carries no cache-busting hash, unlike the one Next's own convention
// emits. That is fine and slightly preferable: the card is regenerated per
// request from live constants, scrapers cache by URL, and a stable URL is one
// fewer thing that changes on every deploy.
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${SITE_NAME} — ${SITE_TAGLINE}`,
};

const LOCAL_ORIGIN = "http://localhost:3000";

// Exported for the test, and separate from the resolution below so the parsing
// rules are checkable without touching process.env. Returns null rather than
// throwing: a malformed value should fall through to the next candidate in the
// chain, not take the build down.
export function normalizeOrigin(raw: string | undefined | null): string | null {
  if (!raw) return null;
  const trimmed = raw.trim();
  if (trimmed === "") return null;

  // Bare hostnames are the common shape of both a hand-typed env var and
  // Vercel's own `VERCEL_PROJECT_PRODUCTION_URL`, which has no scheme at all.
  //
  // The test is `://` rather than `^https?://`, and that distinction is the
  // whole of it: matching only http(s) meant a value with a DIFFERENT scheme
  // fell into the bare-hostname branch, so `ftp://driverpit.com` became
  // `https://ftp://driverpit.com`, which parses cleanly as the host `ftp` and
  // silently roots the entire site at `https://ftp`. Anything declaring a scheme
  // is now held to the protocol check below instead of being rewritten. A bare
  // `localhost:3000` still has no `://`, so it keeps working.
  const withScheme = trimmed.includes("://") ? trimmed : `https://${trimmed}`;

  let url: URL;
  try {
    url = new URL(withScheme);
  } catch {
    return null;
  }
  if (url.protocol !== "http:" && url.protocol !== "https:") return null;

  // Origin only -- any path, query or hash in the env var would be prepended to
  // every canonical URL on the site.
  return url.origin;
}

function resolveSiteUrl(): string {
  return (
    normalizeOrigin(process.env.NEXT_PUBLIC_SITE_URL) ??
    // Vercel sets this to the production domain on every deployment, including
    // previews -- which is what we want, since a preview's canonical should
    // point at production rather than at itself.
    normalizeOrigin(process.env.VERCEL_PROJECT_PRODUCTION_URL) ??
    LOCAL_ORIGIN
  );
}

export const SITE_URL = resolveSiteUrl();

/** Absolute URL for a site-relative path. `"/"` gives the bare origin. */
export function absoluteUrl(path: string): string {
  if (path === "" || path === "/") return SITE_URL;
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;
}
