// Puzzle *numbering* only. Choosing the day's driver deliberately does not
// live here, or anywhere else in TypeScript.
//
// It used to: pickDailyDriverId() hashed the date string (FNV-1a) and took that
// index into the id-sorted pool. That was a good fix for its own predecessor (a
// `daily_puzzles` table precomputed a year ahead, which drifted whenever the
// pool definition changed and had to be regenerated by hand) -- but it made the
// answer a pure function of public inputs, and /daily ships the whole pool with
// ids to the browser for autocomplete. Anyone could recompute the day's driver
// in a console with no network call (audit 2026-07-27 §3.1).
//
// The pick is now a one-time random choice made server-side and pinned in
// daily_targets (drizzle/0038): unpredictable, still incapable of drifting from
// the live pool, still nothing to regenerate. There is no TypeScript mirror of
// it on purpose -- an unpredictable pick has no rules to keep in sync, and a
// reusable "which driver is it today" helper is the thing that leaked.

// First date the old precomputed schedule covered -- kept as the epoch so
// puzzle numbering stays continuous instead of jumping.
const DAILY_EPOCH = "2026-07-18";

function parseUtcDateMs(dateStr: string): number {
  const [year, month, day] = dateStr.split("-").map(Number);
  return Date.UTC(year, month - 1, day);
}

// Safe to compute client-side and safe to display: it says which day it is,
// not who the driver is.
export function getDailyPuzzleNumber(date: string): number {
  const days = Math.round((parseUtcDateMs(date) - parseUtcDateMs(DAILY_EPOCH)) / 86_400_000);
  return days + 1;
}
